import os
import pandas as pd
import glob

# FORCE GRAPHICS TO RUN IN THE BACKGROUND (Bypasses the freeze!)
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

# Clean styling
sns.set_theme(style="whitegrid")

# 1. SETUP PATHS
folder_path = "/home/dawood-raza/Desktop/New Folder/Retail_Sales_Intelligence/Data"

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
csv_files = [f for f in csv_files if "clean_" not in os.path.basename(f) and "my_clean_" not in os.path.basename(f)]

if not csv_files:
    raise FileNotFoundError(f"No original CSV files found in {folder_path}")

file_path = csv_files[0]
print(f"🚀 Found and loading: {os.path.basename(file_path)}\n")

# 2. LOAD & TRANSFORM
df = pd.read_csv(file_path)
df['invoice_date'] = pd.to_datetime(df['invoice_date'], dayfirst=True, errors='coerce')
df['total_revenue'] = df['quantity'] * df['price']

print("=== NUMERICAL SUMMARY STATS ===")
print(df.describe(), "\n")

# 3. SAVE CLEAN DATA TO CSV (Happens safely first!)
output_file = "clean_customer_shopping_data.csv"
output_path = os.path.join(folder_path, output_file)
print(f"💾 Saving clean dataset to: {output_path}...")
df.to_csv(output_path, index=False)
print("✅ Clean file successfully saved!\n")

# 4. GENERATING AND SAVING CHARTS AS IMAGES
print("📊 Generating charts and saving them as images...")

# Chart 1: Demographics Grid
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
sns.histplot(df['age'], bins=20, kde=True, ax=axes[0, 0], color='skyblue')
axes[0, 0].set_title('Customer Age Distribution')

sns.countplot(data=df, x='gender', ax=axes[0, 1], hue='gender', legend=False, palette='pastel')
axes[0, 1].set_title('Gender Distribution')

sns.countplot(data=df, x='payment_method', ax=axes[1, 0], hue='payment_method', legend=False, palette='Set2')
axes[1, 0].set_title('Preferred Payment Methods')

sns.countplot(data=df, y='shopping_mall', ax=axes[1, 1], hue='shopping_mall', legend=False, palette='viridis', order=df['shopping_mall'].value_counts().index)
axes[1, 1].set_title('Transactions by Shopping Mall')

plt.tight_layout()
plt.savefig(os.path.join(folder_path, 'customer_demographics.png'))
plt.close()

# Chart 2: Revenue by Product Category
plt.figure(figsize=(12, 6))
category_revenue = df.groupby('category')['total_revenue'].sum().sort_values(ascending=False).reset_index()
sns.barplot(data=category_revenue, x='category', y='total_revenue', hue='category', legend=False, palette='coolwarm')
plt.title('Total Revenue Generated by Product Category')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig(os.path.join(folder_path, 'revenue_by_category.png'))
plt.close()

print("✅ Charts successfully saved as PNG images!")
print("🏁 Script has reached the very last point successfully.")
